### ISSUE TITLE
请尊重他人的劳动成果，不要盗窃

### ISSUE THREAD

**Issue by wayone** [Andrew5/DHPRO#1]
我好奇，其中有一个仪表盘效果和我做的一模一样，我点进去一看，原来是把我的代码直接搬过来的，只是把文件顶部的版权信息改了一下。太厉害了，我很是怀疑你发出来的其他代码也是这个套路，都是偷来的？

下面链接是我的原版
https://github.com/wayone/Indicator

**Comment by Andrew5** [comment]
之前没有做链接引用，我在此表示歉意，今日我已注明挂引用作者连接，已表明是链接他方代码效果。
